export const CHANNELS = {
  regression: '1455069209523650590',
  freeAgency: '1428099138431746250',
  resigning: '1425556463522414704',
  committee: '1425555499440410812',
  approvedTrades: '1425555422063890443',
  deniedTrades: '1425567560241254520',
};

export const ROLES = {
  staff: {
    commish: 'Paradise Commish',
    schedule: 'Schedule Tracker',
    committee: 'Ghost Paradise Trade Committee',
  },
};

export const TEAM_ALIASES = {
  hawks: 'atlanta_hawks.json',
  atl: 'atlanta_hawks.json',
  nuggets: 'denver_nuggets.json',
  den: 'denver_nuggets.json',
  denver: 'denver_nuggets.json',
  lakers: 'los_angeles_lakers.json',
  lal: 'los_angeles_lakers.json',
  clippers: 'los_angeles_clippers.json',
  lac: 'los_angeles_clippers.json',
  mavs: 'dallas_mavericks.json',
  dallas: 'dallas_mavericks.json',
  knicks: 'new_york_knicks.json',
  nyk: 'new_york_knicks.json',
  nets: 'brooklyn_nets.json',
  bkn: 'brooklyn_nets.json',
  spurs: 'san_antonio_spurs.json',
  sas: 'san_antonio_spurs.json',
  celtics: 'boston_celtics.json',
  bos: 'boston_celtics.json',
  hornets: 'charlotte_hornets.json',
  cha: 'charlotte_hornets.json',
  bulls: 'chicago_bulls.json',
  chi: 'chicago_bulls.json',
  cavs: 'cleveland_cavaliers.json',
  cavaliers: 'cleveland_cavaliers.json',
  cle: 'cleveland_cavaliers.json',
  pistons: 'detroit_pistons.json',
  det: 'detroit_pistons.json',
  warriors: 'golden_state_warriors.json',
  gsw: 'golden_state_warriors.json',
  rockets: 'houston_rockets.json',
  hou: 'houston_rockets.json',
  pacers: 'indiana_pacers.json',
  ind: 'indiana_pacers.json',
  grizzlies: 'memphis_grizzlies.json',
  mem: 'memphis_grizzlies.json',
  heat: 'miami_heat.json',
  mia: 'miami_heat.json',
  bucks: 'milwaukee_bucks.json',
  mil: 'milwaukee_bucks.json',
  wolves: 'minnesota_timberwolves.json',
  timberwolves: 'minnesota_timberwolves.json',
  min: 'minnesota_timberwolves.json',
  pels: 'new_orleans_pelicans.json',
  pelicans: 'new_orleans_pelicans.json',
  pelican: 'new_orleans_pelicans.json',
  neworleanspelicans: 'new_orleans_pelicans.json',
  neworelanspelicans: 'new_orleans_pelicans.json',
  nop: 'new_orleans_pelicans.json',
  la: 'los_angeles_lakers.json',
  laclippers: 'los_angeles_clippers.json',
  knicksalt: 'new_york_knicks.json',
  thunder: 'oklahoma_city_thunder.json',
  okc: 'oklahoma_city_thunder.json',
  magic: 'orlando_magic.json',
  orl: 'orlando_magic.json',
  sixers: 'philadelphia_76ers.json',
  '76ers': 'philadelphia_76ers.json',
  phi: 'philadelphia_76ers.json',
  suns: 'phoenix_suns.json',
  phx: 'phoenix_suns.json',
  blazers: 'portland_trail_blazers.json',
  'trail blazers': 'portland_trail_blazers.json',
  trailblazers: 'portland_trail_blazers.json',
  blazer: 'portland_trail_blazers.json',
  por: 'portland_trail_blazers.json',
  kings: 'sacramento_kings.json',
  sac: 'sacramento_kings.json',
  raptors: 'toronto_raptors.json',
  tor: 'toronto_raptors.json',
  jazz: 'utah_jazz.json',
  uta: 'utah_jazz.json',
  wizards: 'washington_wizards.json',
  was: 'washington_wizards.json',
  fa: 'free_agency.json',
  'free agency': 'free_agency.json',
  'free agent': 'free_agency.json',
};

export const TEAM_FILES = {
  'atlanta hawks': 'atlanta_hawks.json',
  'boston celtics': 'boston_celtics.json',
  'brooklyn nets': 'brooklyn_nets.json',
  'charlotte hornets': 'charlotte_hornets.json',
  'chicago bulls': 'chicago_bulls.json',
  'cleveland cavaliers': 'cleveland_cavaliers.json',
  'dallas mavericks': 'dallas_mavericks.json',
  'denver nuggets': 'denver_nuggets.json',
  'detroit pistons': 'detroit_pistons.json',
  'golden state warriors': 'golden_state_warriors.json',
  'houston rockets': 'houston_rockets.json',
  'indiana pacers': 'indiana_pacers.json',
  'la clippers': 'los_angeles_clippers.json',
  'los angeles clippers': 'los_angeles_clippers.json',
  'los angeles lakers': 'los_angeles_lakers.json',
  'memphis grizzlies': 'memphis_grizzlies.json',
  'miami heat': 'miami_heat.json',
  'milwaukee bucks': 'milwaukee_bucks.json',
  'minnesota timberwolves': 'minnesota_timberwolves.json',
  'new orleans pelicans': 'new_orleans_pelicans.json',
  'new york knicks': 'new_york_knicks.json',
  'oklahoma city thunder': 'oklahoma_city_thunder.json',
  'orlando magic': 'orlando_magic.json',
  'philadelphia 76ers': 'philadelphia_76ers.json',
  'phoenix suns': 'phoenix_suns.json',
  'portland trail blazers': 'portland_trail_blazers.json',
  'sacramento kings': 'sacramento_kings.json',
  'san antonio spurs': 'san_antonio_spurs.json',
  'toronto raptors': 'toronto_raptors.json',
  'utah jazz': 'utah_jazz.json',
  'washington wizards': 'washington_wizards.json',
  'free agency': 'free_agency.json',
};
